// src/businessData.js

const businesses = [
    {
      id: 23890,
      name: 'Business One',
      image: 'https://via.placeholder.com/150/0000FF/FFFFFF?text=Business+One',
      price: 100000,
      revenue: '$10,000',
      monthlyNetProfit: '$35,545.00',
      created: '2022-01-01',
      description: 'A well-established gas station with great traffic.',
      category: 'Gas Station',
      state: 'San Diego, CA',
    },
    {
      id: 23891,
      name: 'Business Two',
      image: 'https://via.placeholder.com/150/FF0000/FFFFFF?text=Business+Two',
      price: 150000,
      revenue: '$15,000',
      monthlyNetProfit: '$5,000',
      created: '2022-01-01',
      description: 'A growing retail store with potential.',
      category: 'Retail',
      state: 'Los Angeles, CA',
    },
    {
      id: 23892,
      name: 'Business Three',
      image: 'https://via.placeholder.com/150/00FF00/FFFFFF?text=Business+Three',
      price: 200000,
      revenue: '$20,000',
      monthlyNetProfit: '$7,500',
      created: '2022-01-01',
      description: 'A cozy restaurant in the heart of the city.',
      category: 'Restaurant',
      state: 'New York, NY',
    },
    {
      id: 23893,
      name: 'Business Four',
      image: 'https://via.placeholder.com/150/FFFF00/FFFFFF?text=Business+Four',
      price: 180000,
      revenue: '$12,000',
      monthlyNetProfit: '$8,000',
      created: '2022-01-01',
      description: 'A tech startup specializing in AI.',
      category: 'Technology & IT',
      state: 'San Francisco, CA',
    },
    {
      id: 23894,
      name: 'Business Five',
      image: 'https://via.placeholder.com/150/FF00FF/FFFFFF?text=Business+Five',
      price: 120000,
      revenue: '$11,000',
      monthlyNetProfit: '$4,000',
      created: '2022-01-01',
      description: 'A local motel with great reviews.',
      category: 'Motel',
      state: 'Miami, FL',
    },
    {
      id: 23895,
      name: 'Business Six',
      image: 'https://via.placeholder.com/150/0000FF/FFFFFF?text=Business+Six',
      price: 130000,
      revenue: '$14,000',
      monthlyNetProfit: '$5,500',
      created: '2022-01-01',
      description: 'An art gallery featuring local artists.',
      category: 'Art Gallery',
      state: 'Chicago, IL',
    },
    {
      id: 23896,
      name: 'Business Seven',
      image: 'https://via.placeholder.com/150/FF0000/FFFFFF?text=Business+Seven',
      price: 160000,
      revenue: '$16,000',
      monthlyNetProfit: '$6,000',
      created: '2022-01-01',
      description: 'A fitness center promoting healthy living.',
      category: 'Fitness Center',
      state: 'Austin, TX',
    },
    {
      id: 23897,
      name: 'Business Eight',
      image: 'https://via.placeholder.com/150/00FFFF/FFFFFF?text=Business+Eight',
      price: 170000,
      revenue: '$17,000',
      monthlyNetProfit: '$6,500',
      created: '2022-01-01',
      description: 'A bakery known for its artisanal bread.',
      category: 'Bakery',
      state: 'Seattle, WA',
    },
    {
      id: 23898,
      name: 'Business Nine',
      image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=Business+Nine',
      price: 140000,
      revenue: '$15,500',
      monthlyNetProfit: '$5,200',
      created: '2022-01-01',
      description: 'A spa offering relaxation and wellness services.',
      category: 'Spa',
      state: 'San Jose, CA',
    },
    {
      id: 23899,
      name: 'Business Ten',
      image: 'https://via.placeholder.com/150/8A2BE2/FFFFFF?text=Business+Ten',
      price: 110000,
      revenue: '$9,000',
      monthlyNetProfit: '$3,500',
      created: '2022-01-01',
      description: 'An online bookstore with a wide selection.',
      category: 'E-commerce',
      state: 'Denver, CO',
    },
    {
      id: 23900,
      name: 'Business Eleven',
      image: 'https://via.placeholder.com/150/FF4500/FFFFFF?text=Business+Eleven',
      price: 155000,
      revenue: '$18,000',
      monthlyNetProfit: '$6,800',
      created: '2022-01-01',
      description: 'A trendy coffee shop with a loyal customer base.',
      category: 'Coffee Shop',
      state: 'Boston, MA',
    },
    {
      id: 23901,
      name: 'Business Twelve',
      image: 'https://via.placeholder.com/150/2E8B57/FFFFFF?text=Business+Twelve',
      price: 145000,
      revenue: '$13,000',
      monthlyNetProfit: '$4,500',
      created: '2022-01-01',
      description: 'A high-end fashion boutique.',
      category: 'Fashion',
      state: 'New York, NY',
    },
    {
      id: 23902,
      name: 'Business Thirteen',
      image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Business+Thirteen',
      price: 165000,
      revenue: '$19,500',
      monthlyNetProfit: '$7,200',
      created: '2022-01-01',
      description: 'An organic farm supplying local markets.',
      category: 'Agriculture',
      state: 'Portland, OR',
    },
    {
      id: 23903,
      name: 'Business Fourteen',
      image: 'https://via.placeholder.com/150/ADFF2F/FFFFFF?text=Business+Fourteen',
      price: 175000,
      revenue: '$20,000',
      monthlyNetProfit: '$8,000',
      created: '2022-01-01',
      description: 'A tech consulting firm helping startups.',
      category: 'Consulting',
      state: 'Los Angeles, CA',
    },
    {
      id: 23904,
      name: 'Business Fifteen',
      image: 'https://via.placeholder.com/150/FF1493/FFFFFF?text=Business+Fifteen',
      price: 135000,
      revenue: '$14,500',
      monthlyNetProfit: '$5,800',
      created: '2022-01-01',
      description: 'A pet grooming service with dedicated clients.',
      category: 'Pet Services',
      state: 'Miami, FL',
    },
    {
      id: 23905,
      name: 'Business Sixteen',
      image: 'https://via.placeholder.com/150/8B0000/FFFFFF?text=Business+Sixteen',
      price: 190000,
      revenue: '$21,000',
      monthlyNetProfit: '$9,000',
      created: '2022-01-01',
      description: 'A local winery producing award-winning wines.',
      category: 'Winery',
      state: 'Napa Valley, CA',
    },
    {
      id: 23906,
      name: 'Business Seventeen',
      image: 'https://via.placeholder.com/150/4682B4/FFFFFF?text=Business+Seventeen',
      price: 165000,
      revenue: '$18,500',
      monthlyNetProfit: '$7,800',
      created: '2022-01-01',
      description: 'A language school teaching multiple languages.',
      category: 'Education',
      state: 'Austin, TX',
    },
    {
      id: 23907,
      name: 'Business Eighteen',
      image: 'https://via.placeholder.com/150/20B2AA/FFFFFF?text=Business+Eighteen',
      price: 150000,
      revenue: '$16,500',
      monthlyNetProfit: '$6,200',
      created: '2022-01-01',
      description: 'A local brewery offering craft beers.',
      category: 'Brewery',
      state: 'Portland, OR',
    },
    {
      id: 23908,
      name: 'Business Nineteen',
      image: 'https://via.placeholder.com/150/000080/FFFFFF?text=Business+Nineteen',
      price: 125000,
      revenue: '$12,500',
      monthlyNetProfit: '$5,000',
      created: '2022-01-01',
      description: 'An adventure tour company for outdoor enthusiasts.',
      category: 'Tourism',
      state: 'Jackson Hole, WY',
    },
    {
      id: 23909,
      name: 'Business Twenty',
      image: 'https://via.placeholder.com/150/FFD700/FFFFFF?text=Business+Twenty',
      price: 175000,
      revenue: '$19,000',
      monthlyNetProfit: '$8,500',
      created: '2022-01-01',
      description: 'A music school offering various classes.',
      category: 'Music Education',
      state: 'San Francisco, CA',
    },
    {
      id: 23910,
      name: 'Business Twenty-One',
      image: 'https://via.placeholder.com/150/FF8C00/FFFFFF?text=Business+Twenty-One',
      price: 145000,
      revenue: '$13,500',
      monthlyNetProfit: '$5,500',
      created: '2022-01-01',
      description: 'A mobile app development company.',
      category: 'Technology',
      state: 'Los Angeles, CA',
    },
    {
      id: 23911,
      name: 'Business Twenty-Two',
      image: 'https://via.placeholder.com/150/8A2BE2/FFFFFF?text=Business+Twenty-Two',
      price: 155000,
      revenue: '$15,000',
      monthlyNetProfit: '$6,800',
      created: '2022-01-01',
      description: 'An event planning service for weddings and parties.',
      category: 'Event Planning',
      state: 'Chicago, IL',
    },
    {
      id: 23912,
      name: 'Business Twenty-Three',
      image: 'https://via.placeholder.com/150/FF6347/FFFFFF?text=Business+Twenty-Three',
      price: 135000,
      revenue: '$12,000',
      monthlyNetProfit: '$4,800',
      created: '2022-01-01',
      description: 'A community garden promoting sustainability.',
      category: 'Agriculture',
      state: 'Seattle, WA',
    },
    {
      id: 23913,
      name: 'Business Twenty-Four',
      image: 'https://via.placeholder.com/150/4682B4/FFFFFF?text=Business+Twenty-Four',
      price: 175000,
      revenue: '$20,500',
      monthlyNetProfit: '$9,200',
      created: '2022-01-01',
      description: 'A digital marketing agency helping local businesses.',
      category: 'Marketing',
      state: 'Austin, TX',
    },
    {
      id: 23914,
      name: 'Business Twenty-Five',
      image: 'https://via.placeholder.com/150/7B68EE/FFFFFF?text=Business+Twenty-Five',
      price: 165000,
      revenue: '$17,500',
      monthlyNetProfit: '$7,700',
      created: '2022-01-01',
      description: 'A cozy bed and breakfast near the beach.',
      category: 'Hospitality',
      state: 'Miami, FL',
    },
    {
      id: 23915,
      name: 'Business Twenty-Six',
      image: 'https://via.placeholder.com/150/DC143C/FFFFFF?text=Business+Twenty-Six',
      price: 140000,
      revenue: '$15,200',
      monthlyNetProfit: '$5,600',
      created: '2022-01-01',
      description: 'A local podcast studio offering recording services.',
      category: 'Media',
      state: 'New York, NY',
    },
    {
      id: 23916,
      name: 'Business Twenty-Seven',
      image: 'https://via.placeholder.com/150/FF69B4/FFFFFF?text=Business+Twenty-Seven',
      price: 150000,
      revenue: '$16,000',
      monthlyNetProfit: '$6,500',
      created: '2022-01-01',
      description: 'A family-owned pizzeria with traditional recipes.',
      category: 'Restaurant',
      state: 'Chicago, IL',
    },
    {
      id: 23917,
      name: 'Business Twenty-Eight',
      image: 'https://via.placeholder.com/150/8B4513/FFFFFF?text=Business+Twenty-Eight',
      price: 180000,
      revenue: '$18,000',
      monthlyNetProfit: '$7,200',
      created: '2022-01-01',
      description: 'An online subscription box service.',
      category: 'E-commerce',
      state: 'San Diego, CA',
    },
    {
      id: 23918,
      name: 'Business Twenty-Nine',
      image: 'https://via.placeholder.com/150/00CED1/FFFFFF?text=Business+Twenty-Nine',
      price: 155000,
      revenue: '$17,000',
      monthlyNetProfit: '$6,900',
      created: '2022-01-01',
      description: 'A computer repair shop with great reviews.',
      category: 'Repair Services',
      state: 'Austin, TX',
    },
    {
      id: 23919,
      name: 'Business Thirty',
      image: 'https://via.placeholder.com/150/00FF7F/FFFFFF?text=Business+Thirty',
      price: 190000,
      revenue: '$19,000',
      monthlyNetProfit: '$8,200',
      created: '2022-01-01',
      description: 'A travel agency offering exotic vacations.',
      category: 'Travel Agency',
      state: 'Miami, FL',
    },
  ];
  
  export default businesses;
  